### ISSUE TITLE
Custom Script support

### ISSUE THREAD

**Issue by maikgreubel** [pulse00/Composer-Eclipse-Plugin#120]
I want to add custom scripts, which calls binaries/script from vendor/bin. This feature is officially supported by composer.

It would be great to add custom scripts instead of the default one (pre-install-cmd, etc.). Otherwise it should be possible to add custom scripts directly to composer.json and the plugin does not remove them at save. Example:

  "scripts": {
    "test": [ "phpunit -c ./tests/phpunit.xml" ],
    "documentation": [ "phpdoc" ]
  }

**Comment by amarcinkowski** [comment]
+1

**Comment by hagnat** [comment]
:+1:

**Comment by lpotherat** [comment]
+1
