### ISSUE TITLE
Switch repository on marketplace entry

### ISSUE THREAD

**Issue by zulus** [pulse00/Composer-Eclipse-Plugin#127]
[Eclipse Marketplace entry](http://marketplace.eclipse.org/content/composer-plugin) points to http://p2-dev.pdt-extensions.org/  i think it's time to replace it by http://p2.pdt-extensions.org/

**Comment by gossi** [comment]
This needs @pulse00 power.

Robert: could you give @zulus and me access on eclipse marketplace plus adding @zulus as member of this repository (+ Java-Composer-Bindings)?

**Comment by pulse00** [comment]
@gossi done. sorry for the delay.

**Comment by pulse00** [comment]
@gossi regarding the marketplace thing: i'd need the email you've registered there.

**Comment by zulus** [comment]
Fixed long time ago
