### ISSUE TITLE
Move to PDT

### ISSUE THREAD

**Issue by zulus** [pulse00/Composer-Eclipse-Plugin#131]
There is a plan to move this plugin into PDT.  [1] [2]

This bug should be an umbrella for tasks to do before upload code into PDT gerrit.

[1] - https://groups.google.com/forum/#!topic/pdt-extensions-platform/Bnh8ugkp0wc
[2] - https://dev.eclipse.org/mhonarc/lists/pdt-dev/msg02930.html

**Comment by gossi** [comment]
I made a wiki article on this one: https://wiki.eclipse.org/PDT/Composer_Migration
And a blog post: http://gos.si/blog/pdt-and-composer-a-visionary-concept

Ref #135

**Comment by zulus** [comment]
I think, that on seprate branch (before-move) we should start collecting code from all repositories and tranform it into org.eclipse.php.composer namespace. I hope we will finish ip-cleanup proces right after Neon.0 release.

This branch should contain:

# This repo
# Composer-Java-Binding (later we can publish it on repo.eclipse.org)
# Part of core-plugin that is used for launching, probably will be moved to php.core or php.commons.core
# Part of gossi/eclipse-components, or migrate to one of eclipse frameworks, probably later moved to php.ui or php.commons.ui

**Comment by gossi** [comment]
I think gossi/eclipse-components isn't used for the composer-plugin (I created it afterwards). I did used it in an experimental branch (just local for me, didn't pushed it). It's a better idea to migrate to one of the eclipse frameworks.

**Comment by zulus** [comment]
Thanks, will be easier for start. Migration to eclipse framework (to something based on EMF) can be performed after code merge.

**Comment by zulus** [comment]
**To all project contributors. Please add +1 if you agree to merge your contribution with PDT.**

Contributors:

* [x] @zulus
* [ ] @gossi 
* [ ] @pulse00 
* [ ] @b4cedev
* [ ] @jpospychala 
* [ ] @pavelhoral 
* [ ] @nataliab (Composer-Java-Bindings)

**Comment by zulus** [comment]
Off course +1 from me.

**Comment by pavelhoral** [comment]
+1

**Comment by zulus** [comment]
@pulse00 @gossi I need comment with +1 in this thread. It's for Eclipse IP team ;)

**Comment by gossi** [comment]
+1 for sure (thought checking myself on the todo-list was meant to be this)

**Comment by b4cedev** [comment]
+1

**Comment by pulse00** [comment]
+1

**Comment by nataliab** [comment]
+1

**Comment by jpospychala** [comment]
+1

**Comment by zulus** [comment]
Thanks to all! I'll prepare initial patch after PDT 4.0 (Neon.0) release.

**Comment by kaloyan-raev** [comment]
+1

**Comment by zulus** [comment]
Initial contribution pushed to PDT gerrit: https://git.eclipse.org/r/#/c/77000/

**Comment by zulus** [comment]
Contribution has been merged. Thank You all.
