### ISSUE TITLE
Replace GIFs by PNGs

### ISSUE THREAD

**Issue by zulus** [pulse00/Composer-Eclipse-Plugin#132]
In dark theme current icons are ugly.

**Comment by gossi** [comment]
Yep, see #100 I close this one as it's a duplicate.

**Comment by zulus** [comment]
Yes and now. Platform still haven't good api for Hi-DPI, and SVG cannot be used as icons. You have to generate rasterized images. 

When plugin will be moved to PDT, replacing gifs will be one of the first tasks (we already did it in PDT and DLTK).
