### ISSUE TITLE
Perspective/Views not showing

### ISSUE THREAD

**Issue by markfaine** [pulse00/Composer-Eclipse-Plugin#134]
Should I get a perspective and/or views?

The only references to Composer I see in the interface is in the File->New Dialog:

Composer Project from existing package
Empty Composer Project

The plugin appeared to install correctly.   I'm using 

Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800

**Comment by gossi** [comment]
There is no view or perspective. There is an editor when you open a `composer.json` and project management helpers, like build path automator.
