### ISSUE TITLE
Switch to WTP JSON editor

### ISSUE THREAD

**Issue by zulus** [pulse00/Composer-Eclipse-Plugin#135]
Angelo Zerr WTP JSON Editor is now part of WTP source code [1]. Will be released as part of WTP 2.0 (Neon release). 

We should consider switch to this editor before merging with PDT.

[1] - https://github.com/angelozerr/eclipse-wtp-json 
[2] - http://git.eclipse.org/c/sourceediting/webtools.sourceediting.git/

**Comment by zulus** [comment]
Patch merged. Closing

**Comment by gossi** [comment]
Very nice! :+1:
