### ISSUE TITLE
Buildpath is lost when running composer > update build path

### ISSUE THREAD

**Issue by pgodiani** [pulse00/Composer-Eclipse-Plugin#142]
My source files are split across several sub-directories that I add to the build path using
the context menu command 'use as a source directory'.
All the dependencies grabbed thru the composer are stored in vendor sub-dir and I use
composer > update build path command to  reflect dependencies changes to build path.
However, this replaces all the build path even directories outside vendor.
Is this working as expected or did I miss something ?

**Comment by zulus** [comment]
This is known limitation of composer plugin. 

Anyway, we are during merge with PDT process [1]. After this I have plan to fix this via two eclipse bugs [2][3]. PDT 4.1 is in RC2 phase, so this probably happen in 4.2.

[1] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=493886
[2] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=472758
[3] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=444226

**Comment by gossi** [comment]
Go to your project preferences > Composer > Build Path Management and then in the upper half, add those directories you want to have in your build path, next to them the plugin is able to auto-detect from composer configuration and installations. Next time you update the build path, those entries will be included as well.

**Comment by zulus** [comment]
@gossi Thanks for care, I completely forgot about this page

**Comment by pgodiani** [comment]
Seems that with the lastest plugin version, inclusion paths are always relative to vendor subtree and hence that feature cannot be used to solve the issue anymore.

**Comment by zulus** [comment]
Fixed in PDT 4.3 (23 March 2017)
