### ISSUE TITLE
Packagist search ignores proxy

### ISSUE THREAD

**Issue by mrezekiel** [pulse00/Composer-Eclipse-Plugin#79]
Please correct me if I am wrong, but it seems that the packagist search completely ignores the proxy settings in eclipse.

I am unable to use this at all behind a proxy and watching the network traffic with wire shark I notice that it was creating a https request to packagist.org.

**Comment by richard-scott** [comment]
Setting the HTTP_PROXY environment variables didn't help me. I have full Internet access for everything in Eclipse and the command line verison of composer works just fine at creating a new Symfony project. 

It's just Version drop down boxk in the "New Symfony Project" window that doesn't work for me. It seems that it is ignoring the detected proxy setup that Eclipse is using.

**Comment by zulus** [comment]
This has been fixed by pulse00/Composer-Java-Bindings#18
